version: 2.1

jobs:
  build-java:
    executor: java
    steps:
      - checkout
      - run:
          name: Build Application
          working_directory: java
          command: ./gradlew :app:build

workflows:
  version: 2
  ci-build:
    jobs:
      - build-java:
          filters:
            tags:
              ignore: /.*/
