version: 2.1

jobs:
  build-java:
    executor: java
    steps:
      - checkout
      - run:
          name: Build Application
          working_directory: java
          command: ./gradlew :app:build

  build-node:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          working_directory: node
          command: npm install
      - run:
          name: Build Application
          working_directory: node
          command: npm run build

workflows:
  version: 2
  ci-build:
    jobs:
      - build-java:
          filters:
            tags:
              ignore: /.*/
      - build-node:
          filters:
            tags:
              ignore: /.*/
