version: 2.1

setup: true

orbs:
  pack: buildpacks/pack@0.2.4
  continuation: circleci/continuation@1.0.0

jobs:
  setup-ci-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Setup CircleCI yml
          command: |
            yq eval-all '. as $item ireduce ({}; . * $item)' .circleci/executors.yml .circleci/ci-build.yml > merged.yml
      - continuation/continue:
          configuration_path: merged.yml

  setup-docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Setup CircleCI yml
          command: |
            yq eval-all '. as $item ireduce ({}; . * $item)' .circleci/executors.yml .circleci/docker-build.yml > merged.yml
      - continuation/continue:
          configuration_path: merged.yml

workflows:
  version: 2
  setup-ci-build:
    jobs:
      - setup-docker-build

  setup-docker-build:
    jobs:
      - setup-docker-build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
