/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import io.micronaut.runtime.Micronaut;

public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}
